export const SET_SERVICES = "SET_SERVICES";
export const SET_SERVICE_DETAILS = "SET_SERVICE_DETAIL";
export const GET_SERVICES = "GET_SERVICES";
export const GET_SERVICE_DETAILS = "GET_SERVICE_DETAILS"
export const SET_ERROR_REQUEST = "SET_ERROR_REQUEST"
export const SET_IS_LOADING = "SET_IS_LOADING"
